#!/usr/bin/env python3
"""Generate synthetic extended-IGT dataset.

Same structure as real IGT (4 decks, probabilistic payoffs), but:
  - 300 trials per participant (3x real IGT)
  - 200 synthetic participants
  - Behavior generated by DIVERSE models from the literature,
    NOT designed to favor any specific predictor

Payoff structure: standard Bechara (1994) IGT schedules, cycled.
  Deck A: +100 per trial, occasional large losses (net EV = -25/trial)
  Deck B: +100 per trial, rare huge loss    (net EV = -25/trial)
  Deck C: +50 per trial, occasional small losses (net EV = +25/trial)
  Deck D: +50 per trial, rare moderate loss (net EV = +25/trial)

Generation models (no single model dominates):
  - Simple RL (EV learning + softmax) — 30%
  - WSLS (win-stay/lose-shift + noise) — 25%
  - Habit (frequency-based inertia) — 20%
  - Random (near-uniform, slight drift) — 15%
  - Mixture (switches strategy mid-task) — 10%
"""

from __future__ import annotations

import json
import math
import os
import random
from dataclasses import dataclass, asdict
from pathlib import Path


# ---------------------------------------------------------------------------
# IGT payoff schedules (standard Bechara 1994, per 10-trial block)
# ---------------------------------------------------------------------------

# Losses in each 10-trial block (wins are constant per deck)
# These cycle every 10 trials
_DECK_WINS = {"A": 100, "B": 100, "C": 50, "D": 50}

# Loss schedules per 10-trial block (standard IGT)
_DECK_LOSS_SCHEDULES = {
    "A": [0, 0, -150, 0, -300, 0, -200, 0, -250, -350],   # 5/10 loss, total=-1250
    "B": [0, 0, 0, 0, 0, 0, 0, 0, 0, -1250],              # 1/10 loss, total=-1250
    "C": [0, 0, -50, 0, -50, 0, -50, 0, -50, -50],         # 5/10 loss, total=-250
    "D": [0, 0, 0, 0, 0, 0, 0, 0, 0, -250],                # 1/10 loss, total=-250
}

ACTIONS = ["A", "B", "C", "D"]
SAFE = {"C", "D"}


def get_outcome(action: str, trial_idx_for_deck: int) -> tuple[float, float]:
    """Return (win, loss) for choosing this deck at this deck-specific trial."""
    win = _DECK_WINS[action]
    block_pos = trial_idx_for_deck % 10
    loss = _DECK_LOSS_SCHEDULES[action][block_pos]
    return float(win), float(loss)


# ---------------------------------------------------------------------------
# Behavior generators (diverse, from literature)
# ---------------------------------------------------------------------------

def _softmax(values: dict[str, float], theta: float, rng: random.Random) -> str:
    """Sample from softmax distribution."""
    max_v = max(values.values())
    exp_vals = {a: math.exp(min(30, theta * (v - max_v))) for a, v in values.items()}
    total = sum(exp_vals.values())
    probs = {a: e / total for a, e in exp_vals.items()}
    r = rng.random()
    cum = 0.0
    for a in ACTIONS:
        cum += probs[a]
        if r <= cum:
            return a
    return ACTIONS[-1]


def generate_simple_rl(n_trials: int, rng: random.Random) -> dict:
    """Simple RL: EV learning + softmax. No prospect theory."""
    # Wide parameter ranges to get diverse profiles (learners AND risk-seekers)
    lr = rng.uniform(0.01, 0.4)         # learning rate
    theta = rng.uniform(0.2, 3.0)       # inverse temperature (lower = more random)
    decay = rng.uniform(0.0, 0.5)       # EV decay (high = forgets, stays risky)

    ev = {a: 0.0 for a in ACTIONS}
    deck_counts = {a: 0 for a in ACTIONS}
    choices, wins, losses = [], [], []

    for t in range(n_trials):
        # Choose
        action = _softmax(ev, theta, rng)
        deck_counts[action] += 1
        w, l = get_outcome(action, deck_counts[action] - 1)

        choices.append(action)
        wins.append(w)
        losses.append(l)

        # Update EV
        outcome = w + l
        ev[action] += lr * (outcome - ev[action])
        for a in ACTIONS:
            ev[a] *= (1.0 - decay)

    return {"model": "simple_rl", "choices": choices, "wins": wins, "losses": losses,
            "params": {"lr": lr, "theta": theta, "decay": decay}}


def generate_wsls(n_trials: int, rng: random.Random) -> dict:
    """Win-stay/lose-shift with noise."""
    stay_prob = rng.uniform(0.5, 0.95)     # P(stay | win)
    shift_prob = rng.uniform(0.3, 0.90)    # P(shift | loss)
    epsilon = rng.uniform(0.05, 0.25)      # random exploration rate

    deck_counts = {a: 0 for a in ACTIONS}
    choices, wins, losses = [], [], []
    prev_action = rng.choice(ACTIONS)
    prev_outcome = 0.0

    for t in range(n_trials):
        if rng.random() < epsilon:
            action = rng.choice(ACTIONS)
        elif t == 0:
            action = rng.choice(ACTIONS)
        elif prev_outcome >= 0:
            # Win: stay with stay_prob
            if rng.random() < stay_prob:
                action = prev_action
            else:
                action = rng.choice([a for a in ACTIONS if a != prev_action])
        else:
            # Loss: shift with shift_prob
            if rng.random() < shift_prob:
                action = rng.choice([a for a in ACTIONS if a != prev_action])
            else:
                action = prev_action

        deck_counts[action] += 1
        w, l = get_outcome(action, deck_counts[action] - 1)
        choices.append(action)
        wins.append(w)
        losses.append(l)
        prev_action = action
        prev_outcome = w + l

    return {"model": "wsls", "choices": choices, "wins": wins, "losses": losses,
            "params": {"stay_prob": stay_prob, "shift_prob": shift_prob, "epsilon": epsilon}}


def generate_habit(n_trials: int, rng: random.Random) -> dict:
    """Frequency-based habit: tends to repeat what it's done most."""
    inertia = rng.uniform(1.5, 8.0)       # how much past frequency matters
    theta = rng.uniform(0.3, 2.0)
    outcome_weight = rng.uniform(0.0, 0.15) # low sensitivity — habit dominates

    counts = {a: 1.0 for a in ACTIONS}  # uniform prior
    ev = {a: 0.0 for a in ACTIONS}
    deck_counts = {a: 0 for a in ACTIONS}
    choices, wins, losses = [], [], []

    for t in range(n_trials):
        # Value = inertia * frequency + small outcome learning
        values = {a: inertia * (counts[a] / sum(counts.values()))
                  + outcome_weight * ev.get(a, 0.0)
                  for a in ACTIONS}
        action = _softmax(values, theta, rng)

        deck_counts[action] += 1
        w, l = get_outcome(action, deck_counts[action] - 1)
        choices.append(action)
        wins.append(w)
        losses.append(l)

        counts[action] += 1.0
        outcome = w + l
        ev[action] += 0.1 * (outcome - ev[action])

    return {"model": "habit", "choices": choices, "wins": wins, "losses": losses,
            "params": {"inertia": inertia, "theta": theta, "outcome_weight": outcome_weight}}


def generate_random(n_trials: int, rng: random.Random) -> dict:
    """Near-random with slight deck bias (simulates inattentive participants)."""
    # Random bias toward 1-2 decks
    bias = {a: rng.uniform(0.5, 2.0) for a in ACTIONS}
    total = sum(bias.values())
    probs = {a: b / total for a, b in bias.items()}

    deck_counts = {a: 0 for a in ACTIONS}
    choices, wins, losses = [], [], []

    for t in range(n_trials):
        r = rng.random()
        cum = 0.0
        action = ACTIONS[-1]
        for a in ACTIONS:
            cum += probs[a]
            if r <= cum:
                action = a
                break

        deck_counts[action] += 1
        w, l = get_outcome(action, deck_counts[action] - 1)
        choices.append(action)
        wins.append(w)
        losses.append(l)

    return {"model": "random", "choices": choices, "wins": wins, "losses": losses,
            "params": {"probs": {a: round(p, 3) for a, p in probs.items()}}}


def generate_mixture(n_trials: int, rng: random.Random) -> dict:
    """Switches strategy partway through (e.g., exploration → exploitation)."""
    switch_point = rng.randint(n_trials // 4, 3 * n_trials // 4)

    # Phase 1: more exploratory
    lr1 = rng.uniform(0.05, 0.2)
    theta1 = rng.uniform(0.2, 1.0)
    # Phase 2: more exploitative
    lr2 = rng.uniform(0.1, 0.5)
    theta2 = rng.uniform(1.5, 4.0)

    ev = {a: 0.0 for a in ACTIONS}
    deck_counts = {a: 0 for a in ACTIONS}
    choices, wins, losses = [], [], []

    for t in range(n_trials):
        lr = lr1 if t < switch_point else lr2
        theta = theta1 if t < switch_point else theta2

        action = _softmax(ev, theta, rng)
        deck_counts[action] += 1
        w, l = get_outcome(action, deck_counts[action] - 1)
        choices.append(action)
        wins.append(w)
        losses.append(l)

        outcome = w + l
        ev[action] += lr * (outcome - ev[action])

    return {"model": "mixture", "choices": choices, "wins": wins, "losses": losses,
            "params": {"switch_point": switch_point, "lr1": lr1, "theta1": theta1,
                       "lr2": lr2, "theta2": theta2}}


# ---------------------------------------------------------------------------
# Dataset generation
# ---------------------------------------------------------------------------

@dataclass
class SyntheticParticipant:
    participant_id: str
    model: str
    n_trials: int
    choices: list[str]
    wins: list[float]
    losses: list[float]
    safe_fraction: float
    params: dict


def generate_dataset(
    n_participants: int = 200,
    n_trials: int = 300,
    seed: int = 12345,
) -> list[SyntheticParticipant]:
    """Generate synthetic extended-IGT dataset."""
    rng = random.Random(seed)

    # Model allocation (no single model dominates)
    model_weights = [
        ("simple_rl", 0.30, generate_simple_rl),
        ("wsls", 0.25, generate_wsls),
        ("habit", 0.20, generate_habit),
        ("random", 0.15, generate_random),
        ("mixture", 0.10, generate_mixture),
    ]

    # Build participant list with model assignments
    assignments = []
    for model_name, frac, gen_fn in model_weights:
        n = int(n_participants * frac)
        assignments.extend([(model_name, gen_fn)] * n)
    # Fill remainder
    while len(assignments) < n_participants:
        model_name, frac, gen_fn = rng.choice(model_weights)
        assignments.append((model_name, gen_fn))
    rng.shuffle(assignments)

    participants = []
    for i, (model_name, gen_fn) in enumerate(assignments):
        data = gen_fn(n_trials, rng)
        choices = data["choices"]
        safe_frac = sum(1 for c in choices if c in SAFE) / len(choices)

        p = SyntheticParticipant(
            participant_id=f"Syn_{i:03d}",
            model=model_name,
            n_trials=n_trials,
            choices=choices,
            wins=data["wins"],
            losses=data["losses"],
            safe_fraction=safe_frac,
            params=data["params"],
        )
        participants.append(p)

    return participants


def save_dataset(participants: list[SyntheticParticipant], path: str) -> None:
    """Save dataset to JSON."""
    data = [asdict(p) for p in participants]
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"  Saved {len(participants)} participants to {path}")


def load_dataset(path: str) -> list[SyntheticParticipant]:
    """Load dataset from JSON."""
    with open(path) as f:
        data = json.load(f)
    return [SyntheticParticipant(**d) for d in data]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 70)
    print("  SYNTHETIC EXTENDED-IGT DATASET GENERATOR")
    print("=" * 70)

    participants = generate_dataset(n_participants=200, n_trials=300, seed=12345)

    # Summary
    from collections import Counter
    model_counts = Counter(p.model for p in participants)
    print(f"\n  Generated {len(participants)} participants × {participants[0].n_trials} trials")
    print(f"\n  Model distribution:")
    for model, count in sorted(model_counts.items()):
        print(f"    {model:<15s}: {count:>3d} ({count/len(participants):.0%})")

    safe_fracs = [p.safe_fraction for p in participants]
    n_learn = sum(1 for f in safe_fracs if f > 0.65)
    n_mixed = sum(1 for f in safe_fracs if 0.35 <= f <= 0.65)
    n_risk = sum(1 for f in safe_fracs if f < 0.35)
    print(f"\n  Behavioral profiles:")
    print(f"    Learners (>65% safe):  {n_learn}")
    print(f"    Mixed (35-65% safe):   {n_mixed}")
    print(f"    Risk-seekers (<35%):   {n_risk}")
    print(f"    Mean safe fraction:    {sum(safe_fracs)/len(safe_fracs):.1%}")

    # Save
    out_dir = os.path.dirname(__file__)
    out_path = os.path.join(out_dir, "synthetic_extended_igt.json")
    save_dataset(participants, out_path)

    # Show a few examples
    print(f"\n  Sample participants:")
    for p in participants[:5]:
        seq = "".join(p.choices[:40])
        print(f"    {p.participant_id} [{p.model:<10s}] safe={p.safe_fraction:.0%}  {seq}...")

    print()
    print("=" * 70)


if __name__ == "__main__":
    main()
